### ISSUE TITLE
Some plots may have used invalid perplexity values?

### ISSUE THREAD

**Issue by lvdmaaten** [distillpub/post--misread-tsne#2]
Hi guys,

I just read the blog post, which is really nice! It should help people in generating hypotheses from the plots they make.

I just had one small remark: you show some results with perplexity 100 that are a complete mess. This mess is likely not due to a property of the algorithm, but due to the implementation you used not catching invalid parameter inputs. Note that the perplexity of a distribution over N items can never be higher then N (in this case, the distribution is uniform). For t-SNE this means you need at least 101 points to be able to use perplexity 100. If you use a perplexity setting that is too high for the number of points (and have no assertion checking for that), the binary search for the right bandwidth will fail and the algorithm produces garbage (depending on the exact implementation). It may be good to mention something like this in the post.

Anyway... other than that I just wanted to say: great work! :-)

Cheers,
-- Laurens

**Comment by wattenberg** [comment]
Thanks, Laurens! That's an excellent point. We added a remark about the issue, and re-ran images with more points for a few of the later images. Thank you so much for pointing this out!
