### ISSUE TITLE
Burnes-Hut tSNE

### ISSUE THREAD

**Issue by DataWaveAnalytics** [distillpub/post--misread-tsne#4]
Thank you for your explanations, nice work.

I would be interesting another "visually attractive" entry to explain the extended version of the algorithm which uses a QuadTree to accelerate computations.

L.J.P. van der Maaten. [Accelerating t-SNE using Tree-Based Algorithms](https://lvdmaaten.github.io/publications/papers/JMLR_2014.pdf). Journal of Machine Learning Research 15(Oct):3221-3245, 2014.

**Comment by colah** [comment]
It would be neat to see a nice visual explanation of that some day. :)

That would be a different project that this one, though.
