### ISSUE TITLE
small typo in section 1, paragraph 2 ('property -> properly')

### ISSUE THREAD

**Issue by bluebelmont** [distillpub/post--misread-tsne#5]
In the sentence 'The image for perplexity 100, with merged clusters, illustrates a pitfall: for the algorithm to operate **property**, the perplexity really should be smaller than the number of points', I believe the authors intended to use the word 'properly'.

**Comment by colah** [comment]
Thanks for pointing this out. Fixed by 172f676. Changes will propagate to the live site in a bit.
