### ISSUE TITLE
Typo in section "3. Distances between clusters might not mean anything"

### ISSUE THREAD

**Issue by RahulBhalley** [distillpub/post--misread-tsne#7]
In second paragraph, the last sentence says, _Since perplexity 50 gave us a good picture in this example, can we can always set perplexity to 50 if we want to see global geometry?_ where instead of **can we can always** it should be **so can we always**. 
After the above suggested change the sentence would be _Since perplexity 50 gave us a good picture in this example,_ **so can we always** _set perplexity to 50 if we want to see global geometry?_ 
@enjalot @colah please fix this.

**Comment by colah** [comment]
Fixed! Thanks for pointing that out.

(In the future, please feel free to make a pull request!)
